#!/usr/bin/env python3
"""
fetch_dat.py — NOAA Damage Assessment Toolkit proximity fetcher
https://github.com/Metspy/svrwx-aap

Queries the NWS DAT ArcGIS FeatureServer for all three layer types (points,
lines, polygons) within a configurable bounding box around a reference point,
merges results into a local GeoJSON cache, and flushes records outside the
retention window.

All user-configurable values live in config.json — do not edit this file
unless you are changing the tool's behaviour.

Designed for daily cron use. Minimises API queries by fetching only records
since the last successful run (with a 3-day overlap for late NWS submissions).

Usage:
    python fetch_dat.py                # incremental update
    python fetch_dat.py --backfill     # fetch from config start_date
    python fetch_dat.py --config /path/to/other/config.json
    python fetch_dat.py --help

Cron example (daily at 06:00, then auto-commit):
    0 6 * * * cd /path/to/svrwx-aap && \\
        .venv/bin/python fetch_dat.py && \\
        git add data/dat_cache.json && \\
        git commit -m "DAT update $(date +\\%Y-\\%m-\\%d)" && \\
        git push >> /tmp/dat_fetch.log 2>&1
"""

import json
import sys
import time
import argparse
import logging
import urllib.request
import urllib.parse
import urllib.error
from datetime import datetime, timezone, timedelta
from math import radians, cos, sin, asin, sqrt
from pathlib import Path

# ── Constants (not user-configurable) ────────────────────────────────────────

DAT_BASE  = "https://services.dat.noaa.gov/arcgis/rest/services/nws_damageassessmenttoolkit/DamageViewer/FeatureServer"
PAGE_SIZE = 2000   # DAT API hard limit

# (layer_id, esri_geometry_type, date_field_for_where_clause)
# points:   stormdate often NULL; surveydate is reliable
# lines:    no surveydate; stormdate IS populated
# polygons: neither stormdate nor surveydate reliable; created_date is the best proxy
LAYERS = {
    "points":   (0, "esriGeometryPoint",   "surveydate"),
    "lines":    (1, "esriGeometryPolyline", "stormdate"),
    "polygons": (2, "esriGeometryPolygon",  "created_date"),
}

SCRIPT_DIR = Path(__file__).parent

# ── Logging ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%SZ",
)
log = logging.getLogger("svrwx-aap")


# ── Config loading ────────────────────────────────────────────────────────────

def load_config(path: Path) -> dict:
    """Load and validate config.json, returning a flat settings dict."""
    if not path.exists():
        log.error("Config file not found: %s", path)
        log.error("Copy config.json.example to config.json and edit it.")
        sys.exit(1)

    with open(path) as fh:
        raw = json.load(fh)

    # Validate required keys
    required = [
        ("site", "lat"), ("site", "lon"), ("site", "name"),
        ("filter", "radius_km"), ("filter", "start_date"),
    ]
    for section, key in required:
        if key not in raw.get(section, {}):
            log.error("Missing config key: %s.%s", section, key)
            sys.exit(1)

    site   = raw["site"]
    filt   = raw["filter"]
    disp   = raw.get("display", {})

    start_date = datetime.strptime(filt["start_date"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
    end_date_str = filt.get("end_date")
    end_date = (
        datetime.strptime(end_date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        if end_date_str else None
    )

    radius_km      = float(filt["radius_km"])
    retention_days = int(filt.get("retention_days", 400))

    # Derive a sensible retention if not specified:
    # cover start_date → end_date (or today) + 30-day margin
    horizon = end_date or datetime.now(timezone.utc)
    campaign_days = (horizon - start_date).days + 30
    if retention_days < campaign_days:
        log.warning(
            "retention_days=%d is shorter than the campaign span (%d days). "
            "Consider increasing it in config.json.",
            retention_days, campaign_days,
        )

    # bbox half-width: radius_km converted to degrees (1° lat ≈ 111 km) + 10% pad
    bbox_deg = (radius_km / 111.0) * 1.1

    # Validate and normalise custom markers
    raw_markers = raw.get("markers", [])
    markers = []
    for i, m in enumerate(raw_markers):
        if "lat" not in m or "lon" not in m or "name" not in m:
            log.warning("markers[%d] missing required lat/lon/name — skipped", i)
            continue
        markers.append({
            "name":        str(m["name"]),
            "lat":         float(m["lat"]),
            "lon":         float(m["lon"]),
            "color":       str(m.get("color", "#ffffff")),
            "symbol":      str(m.get("symbol", "circle")).lower(),
            "description": str(m.get("description", "")),
        })

    return {
        "site_name":       site["name"],
        "site_short":      site.get("short_name", site["name"]),
        "site_desc":       site.get("description", ""),
        "site_lat":        float(site["lat"]),
        "site_lon":        float(site["lon"]),
        "radius_km":       radius_km,
        "start_date":      start_date,
        "end_date":        end_date,
        "retention_days":  retention_days,
        "bbox_deg":        bbox_deg,
        "default_window":  int(disp.get("default_window_days", 30)),
        "map_zoom":        int(disp.get("map_zoom", 7)),
        "ring_distances":  disp.get("ring_distances_km", []),
        "markers":         markers,
    }


# ── Geometry helpers ──────────────────────────────────────────────────────────

def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Return great-circle distance in km."""
    R = 6371.0
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat / 2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2)**2
    return R * 2 * asin(sqrt(a))


def geojson_centroid(geom: dict) -> tuple:
    """Return (lat, lon) centroid of a GeoJSON geometry, or (None, None)."""
    if not geom:
        return None, None
    gtype = geom.get("type", "")
    coords = geom.get("coordinates")
    if not coords:
        return None, None

    if gtype == "Point":
        return coords[1], coords[0]

    # Flatten all coordinate pairs for any multi-part geometry
    flat = []
    def _flatten(c):
        if not c:
            return
        if isinstance(c[0], (int, float)):
            flat.append(c)
        else:
            for item in c:
                _flatten(item)
    _flatten(coords)

    if not flat:
        return None, None
    return (
        sum(c[1] for c in flat) / len(flat),
        sum(c[0] for c in flat) / len(flat),
    )


def feature_near_site(feature: dict, cfg: dict) -> bool:
    """Return True if the feature's centroid is within cfg['radius_km'] of the site."""
    lat, lon = geojson_centroid(feature.get("geometry"))

    if lat is None:
        # Fall back to attribute-level lat/lon (DAT points carry these)
        p = feature.get("properties", {})
        lat, lon = p.get("lat"), p.get("lon")

    if lat is None or lon is None:
        return False

    return haversine(cfg["site_lat"], cfg["site_lon"], lat, lon) <= cfg["radius_km"]


# ── Esri JSON → GeoJSON ───────────────────────────────────────────────────────

def esri_to_geojson_geom(esri_geom: dict, esri_type: str) -> dict | None:
    """Convert an Esri REST geometry object to a GeoJSON geometry dict."""
    if not esri_geom:
        return None
    if esri_type == "esriGeometryPoint":
        x, y = esri_geom.get("x"), esri_geom.get("y")
        if x is None or y is None:
            return None
        return {"type": "Point", "coordinates": [x, y]}
    if esri_type == "esriGeometryPolyline":
        paths = esri_geom.get("paths", [])
        if len(paths) == 1:
            return {"type": "LineString",      "coordinates": paths[0]}
        return             {"type": "MultiLineString", "coordinates": paths}
    if esri_type == "esriGeometryPolygon":
        rings = esri_geom.get("rings", [])
        if len(rings) == 1:
            return {"type": "Polygon",      "coordinates": rings}
        return             {"type": "MultiPolygon", "coordinates": [[r] for r in rings]}
    return None


# ── API helpers ───────────────────────────────────────────────────────────────

def _epoch_ms(dt: datetime) -> int:
    return int(dt.timestamp() * 1000)


def _build_bbox(cfg: dict) -> str:
    d = cfg["bbox_deg"]
    return json.dumps({
        "xmin": cfg["site_lon"] - d,
        "ymin": cfg["site_lat"] - d,
        "xmax": cfg["site_lon"] + d,
        "ymax": cfg["site_lat"] + d,
        "spatialReference": {"wkid": 4326},
    })


def _since_where(since_dt: datetime, date_field: str) -> str:
    """
    Build the WHERE clause for date filtering.

    Layer date fields differ:
      - points/polygons: 'stormdate' is NULL on older records; use 'surveydate'
        which is reliably populated (date the NWS survey was submitted).
      - lines: has no 'surveydate' field; 'stormdate' IS populated on line records.

    The Esri server requires a TIMESTAMP literal, not a raw epoch integer.
    """
    return "{} >= TIMESTAMP '{}'".format(date_field, since_dt.strftime("%Y-%m-%d %H:%M:%S"))


def query_layer(layer_id: int, since_dt: datetime, bbox: str, date_field: str, offset: int = 0) -> dict:
    """
    Issue one paginated query against a DAT FeatureServer layer.
    Returns the raw Esri JSON response dict (may be empty on error).
    """
    url = f"{DAT_BASE}/{layer_id}/query"
    params = {
        "f":                 "json",
        "where":             _since_where(since_dt, date_field),
        "geometry":          bbox,
        "geometryType":      "esriGeometryEnvelope",
        "spatialRel":        "esriSpatialRelIntersects",
        "inSR":              "4326",
        "outSR":             "4326",
        "outFields":         "*",
        "returnGeometry":    "true",
        "resultOffset":      str(offset),
        "resultRecordCount": str(PAGE_SIZE),
        "orderByFields":     "stormdate ASC",
    }
    full_url = f"{url}?{urllib.parse.urlencode(params)}"
    log.debug("GET %s", full_url)
    req = urllib.request.Request(
        full_url,
        headers={"User-Agent": "svrwx-aap/1.0 (https://github.com/YOUR-USERNAME/svrwx-aap)"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
            log.debug("Response (%d bytes): %s", len(raw), raw[:300])
            data = json.loads(raw)
            if "error" in data:
                log.error("API error on layer %d: %s", layer_id, data["error"])
                return {}
            return data
    except urllib.error.HTTPError as e:
        log.error("HTTP %s on layer %d: %s", e.code, layer_id, e.reason)
    except Exception as e:
        log.error("Request error on layer %d: %s", layer_id, e)
    return {}


def fetch_layer(layer_name: str, cfg: dict, since_dt: datetime) -> list:
    """
    Paginate through a DAT layer and return nearby GeoJSON features.
    Each feature gets a 'layer' property set to layer_name.
    """
    layer_id, esri_type, date_field = LAYERS[layer_name]
    bbox     = _build_bbox(cfg)
    features = []
    offset   = 0

    while True:
        log.info("  %-8s  offset=%-5d  since=%s", layer_name, offset, since_dt.date())
        data = query_layer(layer_id, since_dt, bbox, date_field, offset)

        batch = data.get("features", [])
        if not batch and offset == 0:
            log.warning("  %-8s  no features returned", layer_name)
            break

        for f in batch:
            attrs = dict(f.get("attributes", {}))
            # Normalise layer-specific field names to consistent keys for the viewer
            if layer_name == "lines":
                attrs.setdefault("deaths",    attrs.get("fatalities"))
                attrs.setdefault("windspeed", str(attrs["maxwind"]) if attrs.get("maxwind") else None)
                attrs.setdefault("office",    attrs.get("wfo"))
                attrs.setdefault("surveydate", attrs.get("stormdate"))
                # centroid fallback: midpoint of start/end coords
                if attrs.get("startlat") and attrs.get("startlon")                    and attrs.get("endlat") and attrs.get("endlon"):
                    attrs.setdefault("lat", (attrs["startlat"] + attrs["endlat"]) / 2)
                    attrs.setdefault("lon", (attrs["startlon"] + attrs["endlon"]) / 2)
            elif layer_name == "polygons":
                attrs.setdefault("deaths",    attrs.get("fatalities"))
                # surveydate alias so flush_old and the viewer date logic work uniformly
                attrs.setdefault("surveydate", attrs.get("created_date") or attrs.get("last_edited_date"))
                # Sentinel value cleanup: -99 means "not recorded"
                for sentinel_field in ("length", "width", "injuries", "fatalities", "deaths"):
                    if attrs.get(sentinel_field) == -99:
                        attrs[sentinel_field] = None
            geojson_f = {
                "type":       "Feature",
                "geometry":   esri_to_geojson_geom(f.get("geometry"), esri_type),
                "properties": {**attrs, "layer": layer_name},
            }
            if feature_near_site(geojson_f, cfg):
                features.append(geojson_f)

        if len(batch) < PAGE_SIZE or not data.get("exceededTransferLimit", False):
            break

        offset += PAGE_SIZE
        time.sleep(0.4)

    log.info("  %-8s  %d within %.0f km", layer_name, len(features), cfg["radius_km"])
    return features


# ── Cache management ──────────────────────────────────────────────────────────

def cache_path(cfg: dict) -> Path:
    return SCRIPT_DIR / "data" / "dat_cache.json"


def load_cache(cfg: dict) -> dict:
    path = cache_path(cfg)
    if path.exists():
        try:
            with open(path) as fh:
                return json.load(fh)
        except Exception as e:
            log.warning("Could not read cache (%s) — starting fresh.", e)
    return {
        "meta": {
            "site_name":      cfg["site_name"],
            "site_short":     cfg["site_short"],
            "site_lat":       cfg["site_lat"],
            "site_lon":       cfg["site_lon"],
            "radius_km":      cfg["radius_km"],
            "start_date":     cfg["start_date"].isoformat(),
            "ring_distances": cfg["ring_distances"],
            "default_window": cfg["default_window"],
            "map_zoom":       cfg["map_zoom"],
            "markers":        cfg["markers"],
            "last_fetch":     None,
            "generated":      None,
        },
        "features": [],
    }


def save_cache(cache: dict, cfg: dict):
    path = cache_path(cfg)
    path.parent.mkdir(parents=True, exist_ok=True)
    cache["meta"]["generated"] = datetime.now(timezone.utc).isoformat()
    # Always keep meta in sync with current config
    cache["meta"].update({
        "site_name":      cfg["site_name"],
        "site_short":     cfg["site_short"],
        "site_lat":       cfg["site_lat"],
        "site_lon":       cfg["site_lon"],
        "radius_km":      cfg["radius_km"],
        "ring_distances": cfg["ring_distances"],
        "default_window": cfg["default_window"],
        "map_zoom":       cfg["map_zoom"],
        "markers":        cfg["markers"],
    })
    tmp = path.with_suffix(".tmp")
    with open(tmp, "w") as fh:
        json.dump(cache, fh, separators=(",", ":"))
    tmp.rename(path)
    log.info("Saved %s  (%.1f KB, %d features)",
             path, path.stat().st_size / 1024, len(cache["features"]))


def flush_old(cache: dict, cfg: dict) -> int:
    """Remove features whose effective date predates the retention window.

    Uses surveydate as the primary date field (stormdate is NULL on many records).
    Falls back to stormdate if surveydate is also absent.
    """
    cutoff_ms = _epoch_ms(datetime.now(timezone.utc) - timedelta(days=cfg["retention_days"]))
    # Also respect config start_date as a hard floor
    start_ms  = _epoch_ms(cfg["start_date"])
    floor_ms  = max(cutoff_ms, start_ms)

    def effective_date_ms(f):
        p = f.get("properties", {})
        return p.get("surveydate") or p.get("stormdate") or 0

    before = len(cache["features"])
    cache["features"] = [
        f for f in cache["features"]
        if effective_date_ms(f) >= floor_ms
    ]
    removed = before - len(cache["features"])
    if removed:
        log.info("Flushed %d features outside retention window.", removed)
    return removed


def merge(existing: list, new_features: list) -> tuple[list, int]:
    """Merge new features into existing, de-duplicating by globalid."""
    seen = {
        f["properties"]["globalid"]
        for f in existing
        if f.get("properties", {}).get("globalid")
    }
    added = 0
    for f in new_features:
        gid = f.get("properties", {}).get("globalid")
        if gid and gid in seen:
            continue
        existing.append(f)
        if gid:
            seen.add(gid)
        added += 1
    return existing, added


# ── Main ──────────────────────────────────────────────────────────────────────

def run(cfg: dict, backfill: bool = False):
    site = cfg["site_name"]
    log.info("=== svrwx-aap  site=%r  r=%.0f km ===", site, cfg["radius_km"])

    cache = load_cache(cfg)

    # Determine fetch start
    if backfill or cache["meta"]["last_fetch"] is None:
        since = cfg["start_date"]
        log.info("Backfill from %s", since.date())
    else:
        last  = datetime.fromisoformat(cache["meta"]["last_fetch"])
        since = last - timedelta(days=3)   # 3-day overlap for late NWS submissions
        log.info("Incremental fetch from %s (3-day overlap)", since.date())

    # Respect end_date cap
    if cfg["end_date"] and since > cfg["end_date"]:
        log.info("Current date is past end_date (%s) — nothing to fetch.", cfg["end_date"].date())
        return

    # Fetch all three layers
    all_new = []
    for layer_name in LAYERS:
        all_new.extend(fetch_layer(layer_name, cfg, since))

    cache["features"], added = merge(cache["features"], all_new)
    log.info("Merged %d new features (total pre-flush: %d)", added, len(cache["features"]))

    flush_old(cache, cfg)

    cache["meta"]["last_fetch"] = datetime.now(timezone.utc).isoformat()
    save_cache(cache, cfg)
    log.info("=== Done. Cache has %d features ===", len(cache["features"]))


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Fetch NWS DAT severe weather records near a configured reference point.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python fetch_dat.py                          # incremental daily update
  python fetch_dat.py --backfill               # full fetch from config start_date
  python fetch_dat.py --config ~/my/config.json
        """,
    )
    parser.add_argument(
        "--backfill",
        action="store_true",
        help="Ignore last_fetch and re-fetch from config start_date.",
    )
    parser.add_argument(
        "--config",
        default=str(SCRIPT_DIR / "config.json"),
        metavar="PATH",
        help="Path to config.json (default: config.json next to this script).",
    )
    args = parser.parse_args()

    cfg = load_config(Path(args.config))
    run(cfg, backfill=args.backfill)
